# Generated by Django 6.0.3 on 2026-03-22 00:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
