# Generated by Django 6.0.3 on 2026-03-22 00:46

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_enrolled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled_on',
            field=models.DateField(default=students.models.get_today),
        ),
    ]
